import Footer from "./components/Footer"
import "./styles/globals.css";
import Navbar from "./components/Navbar"
import { Providers } from "./provider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>
        <Navbar/>
        <main>
          <Providers>{children} </Providers>
        </main>
        <Footer />
      </body>
    </html>
  )
}
